name: 'HELLO world'

description: 'saying HELLO'

inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: #id of output
    description: 'Time '
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.who-to-greet }}